name: Patata
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  desplegarEnVPS:
    runs-on: ubuntu-latest
    name: Patata
    steps:
    - uses: actions/checkout@v2.3.4
      env:
        VPN_EMAIL: ${{ secrets.VPN_EMAIL }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        HOP_SERVER: ${{ secrets.HOP_SERVER }}
        HOP_PASSWORD: ${{ secrets.HOP_PASSWORD }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    - name: Instalar VPNC
      run: |
          echo -en "IPSEC gateway galeria.ucm.es\n IPSEC ID ucm\n IPSEC secret ucm\n XAuth username $VPN_EMAIL\n XAuth obfuscated password $VPN_PASSWORD" > vpn.conf
          cat vpn.conf
